/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.edu.view;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import poly.edu.service.SharedData;

/**
 *
 * @author Asus
 */
public class MAIN_FORM extends javax.swing.JFrame {

    private MANAGEMENT_STUDENTS qlsv;
    private MANAGEMENT_SCORE_STUDENTS qldsv;

    public MAIN_FORM() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("HỆ THỐNG ĐÀO TẠO FPOLY");

//        pnnContainer.setPreferredSize(new Dimension(1000, 700));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        btnLoguot = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnManagementStudent = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnManagementScoreStudent = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        pnnContainer = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTypeAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        jMenuBar3 = new javax.swing.JMenuBar();
        mnUser = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        mnManagement = new javax.swing.JMenu();
        mnManagementStudent = new javax.swing.JMenuItem();
        mnManagementScoreStudent = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();
        mnIntroduce = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnLoguot.setText("Đăng Xuất");
        btnLoguot.setFocusable(false);
        btnLoguot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoguot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoguot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoguotActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoguot);
        jToolBar1.add(jSeparator1);

        btnManagementStudent.setText("Quản Lí Sinh Viên");
        btnManagementStudent.setFocusable(false);
        btnManagementStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManagementStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManagementStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManagementStudent);
        jToolBar1.add(jSeparator2);

        btnManagementScoreStudent.setText("Quản Lí Điểm Sinh Viên");
        btnManagementScoreStudent.setFocusable(false);
        btnManagementScoreStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManagementScoreStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManagementScoreStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementScoreStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManagementScoreStudent);
        jToolBar1.add(jSeparator3);

        btnExit.setText("Thoát ");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        lblTypeAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTypeAccount.setForeground(new java.awt.Color(255, 0, 51));
        lblTypeAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Login with role  : ");

        txtRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRole.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblTypeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTypeAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mnUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnUser.setText("User");

        mnLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnLogin.setText("Đăng nhập");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });
        mnUser.add(mnLogin);

        mnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnExit.setText("Thoát !");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnUser.add(mnExit);

        jMenuBar3.add(mnUser);

        mnManagement.setText("Management");

        mnManagementStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnManagementStudent.setText("Quản Lí Sinh Viên");
        mnManagementStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnManagementStudentActionPerformed(evt);
            }
        });
        mnManagement.add(mnManagementStudent);

        mnManagementScoreStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnManagementScoreStudent.setText("Quản Lí Điểm Sinh Viên");
        mnManagementScoreStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnManagementScoreStudentActionPerformed(evt);
            }
        });
        mnManagement.add(mnManagementScoreStudent);

        jMenuBar3.add(mnManagement);

        mnAbout.setText("Help");

        mnIntroduce.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnIntroduce.setText("Giới Thiệu");
        mnAbout.add(mnIntroduce);

        mnHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnHelp.setText("Trợ giúp ");
        mnAbout.add(mnHelp);

        jMenuBar3.add(mnAbout);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnManagementScoreStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnManagementScoreStudentActionPerformed
        if (qldsv == null) {
            try {
                qldsv = new MANAGEMENT_SCORE_STUDENTS();
            } catch (Exception ex) {
                Logger.getLogger(MAIN_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
            pnnContainer.addTab("QUẢN LÍ ĐIỂM SINH VIÊN", qldsv);
        }
        pnnContainer.setSelectedComponent(qldsv);
    }//GEN-LAST:event_mnManagementScoreStudentActionPerformed

    private void mnManagementStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnManagementStudentActionPerformed
        if (qlsv == null) {
            try {
                qlsv = new MANAGEMENT_STUDENTS();
            } catch (Exception ex) {
                Logger.getLogger(MAIN_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
            pnnContainer.addTab("QUẢN LÍ SINH VIÊN", qlsv);
        }
        pnnContainer.setSelectedComponent(qlsv);
    }//GEN-LAST:event_mnManagementStudentActionPerformed

    private void btnManagementStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementStudentActionPerformed
        if (qlsv == null) {
            try {
                qlsv = new MANAGEMENT_STUDENTS();
            } catch (Exception ex) {
                Logger.getLogger(MAIN_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
            pnnContainer.addTab("QUẢN LÍ SINH VIÊN", qlsv);
        }
        pnnContainer.setSelectedComponent(qlsv);
    }//GEN-LAST:event_btnManagementStudentActionPerformed

    private void btnManagementScoreStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementScoreStudentActionPerformed
        if (qldsv == null) {
            try {
                qldsv = new MANAGEMENT_SCORE_STUDENTS();
            } catch (Exception ex) {
                Logger.getLogger(MAIN_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
            pnnContainer.addTab("QUẢN LÍ ĐIỂM SINH VIÊN", qldsv);
        }
        pnnContainer.setSelectedComponent(qldsv);
    }//GEN-LAST:event_btnManagementScoreStudentActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LOGIN_FORM login = new LOGIN_FORM(this, true);
        login.setVisible(true);
        LoginsuccesFully();

    }//GEN-LAST:event_formWindowOpened

    private void btnLoguotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoguotActionPerformed
        LOGIN_FORM login = new LOGIN_FORM(this, true);
        login.setVisible(true);
//        pnnContainer.removeAll();
        LoginsuccesFully();


    }//GEN-LAST:event_btnLoguotActionPerformed

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        LOGIN_FORM login = new LOGIN_FORM(this, true);
        login.setVisible(true);
        LoginsuccesFully();
//        pnnContainer.removeAll();
    }//GEN-LAST:event_mnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không  ? ", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (chon != JOptionPane.YES_OPTION) {
            return;
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed
//    private void LoginsuccesFully() {
//        try {
//            // Remove all elements related to the previous role
//            mnManagementStudent.setEnabled(false);
//            mnManagementScoreStudent.setEnabled(false);
//            btnManagementStudent.setEnabled(false);
//            btnManagementScoreStudent.setEnabled(false);
//
//            if (SharedData.nguoiDangnhap != null) {
//                lblTypeAccount.setText(SharedData.nguoiDangnhap.getTendangnhap());
//                txtRole.setText(SharedData.nguoiDangnhap.getVaitro());
//
//                String role = SharedData.nguoiDangnhap.getVaitro();
//
//                if ("daotao".equals(role)) {
//                    mnManagementStudent.setEnabled(true);
//                    btnManagementStudent.setEnabled(true);
//                } else if ("giangvien".equals(role)) {
//                    mnManagementScoreStudent.setEnabled(true);
//                    btnManagementScoreStudent.setEnabled(true);
//                } else {
//                    // Handle unknown role if needed
//                }
//            } else {
//                // Handle null user data if needed
//            }
//        } catch (Exception e) {
//            e.printStackTrace(); // Print the error for debugging
//            // Handle the exception, e.g., display an error message
//            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }

//    private void LoginsuccesFully() {
//    try {
//        if (SharedData.nguoiDangnhap != null) {
//            lblTypeAccount.setText(SharedData.nguoiDangnhap.getTendangnhap());
//            txtRole.setText(SharedData.nguoiDangnhap.getVaitro());
//
//            String role = SharedData.nguoiDangnhap.getVaitro();
//
//            if ("daotao".equals(role)) {
//                mnManagementStudent.setEnabled(true);
//                mnManagementScoreStudent.setEnabled(false);
//                btnManagementStudent.setEnabled(true);
//                btnManagementScoreStudent.setEnabled(false);
//            } else if ("giangvien".equals(role)) {
//                mnManagementScoreStudent.setEnabled(true);
//                mnManagementStudent.setEnabled(false);
//                btnManagementScoreStudent.setEnabled(true);
//                btnManagementStudent.setEnabled(false);
//            } else {
//                // Handle unknown role if needed
//            }
//        } else {
//            // Handle null user data if needed
//        }
//    } catch (Exception e) {
//        e.printStackTrace(); // Print the error for debugging
//        // Handle the exception, e.g., display an error message
//        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
//}
    private void LoginsuccesFully() {
        try {
            lblTypeAccount.setText(SharedData.nguoiDangnhap.getTendangnhap());
            txtRole.setText(SharedData.nguoiDangnhap.getVaitro());
           
            if (SharedData.nguoiDangnhap.getVaitro().equals("daotao")) {
                pnnContainer.removeAll();
                mnManagementStudent.setEnabled(true);
                mnManagementScoreStudent.setEnabled(false);
                btnManagementStudent.setEnabled(true);
                btnManagementScoreStudent.setEnabled(false);
            } else if (SharedData.nguoiDangnhap.getVaitro().equals("giangvien")) {
                pnnContainer.removeAll();
                mnManagementScoreStudent.setEnabled(true);
                mnManagementStudent.setEnabled(false);
                btnManagementScoreStudent.setEnabled(true);
                btnManagementStudent.setEnabled(false);
            }
        } catch (Exception e) {
            System.out.println("Lỗi  "+e);
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoguot;
    private javax.swing.JButton btnManagementScoreStudent;
    private javax.swing.JButton btnManagementStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTypeAccount;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnHelp;
    private javax.swing.JMenuItem mnIntroduce;
    private javax.swing.JMenuItem mnLogin;
    private javax.swing.JMenu mnManagement;
    private javax.swing.JMenuItem mnManagementScoreStudent;
    private javax.swing.JMenuItem mnManagementStudent;
    private javax.swing.JMenu mnUser;
    private javax.swing.JTabbedPane pnnContainer;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
