/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poly.edu.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;
import poly.edu.model.GRADES;
import poly.edu.model.STUDENTS;
import poly.edu.reponsitory.DATABASE_CONNECT;
import poly.edu.reponsitory.GRADE_REPONSITORY;
import poly.edu.service.GRADE_SERVICE;
import poly.edu.service.STUDENTS_SERVICE;

/**
 *
 * @author Asus
 */
public class MANAGEMENT_SCORE_STUDENTS extends javax.swing.JPanel {

    private int index;
    private final GRADE_SERVICE gds = new GRADE_SERVICE();
    private final GRADE_REPONSITORY drrp = new GRADE_REPONSITORY();
    private DefaultTableModel model = new DefaultTableModel();

    public MANAGEMENT_SCORE_STUDENTS() throws Exception {
        initComponents();
        model = (DefaultTableModel) tblScoreST.getModel();
        LoadToTable();

    }

    public void tinhdiemTB() {
        if (txtTiengAnh.equals("") || txtTinHoc.equals("") || txtGDTC.equals("")) {
            return;
        }
        float tienganh = Float.parseFloat(txtTiengAnh.getText());
        float tinhoc = Float.parseFloat(txtTinHoc.getText());
        float tgdtc = Float.parseFloat(txtGDTC.getText());
        float ketqua = (tienganh + tinhoc + tgdtc) / 3;
        String formattedKetQua = String.format("%.1f", ketqua); // Format ketqua to have two decimal places
        txtDiemTrungBinh.setText(formattedKetQua);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pnnSearch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaSinhVien = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblTenSinhVien = new javax.swing.JLabel();
        lblTenSV = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblSDT1 = new javax.swing.JLabel();
        btnNewDST = new javax.swing.JButton();
        txtTenSinhVien = new javax.swing.JTextField();
        txtMaSV = new javax.swing.JTextField();
        txtTiengAnh = new javax.swing.JTextField();
        txtTinHoc = new javax.swing.JTextField();
        txtGDTC = new javax.swing.JTextField();
        btnSaveDSV = new javax.swing.JButton();
        btnUpdateDSV = new javax.swing.JButton();
        btnDeleteDSV = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblScoreST = new javax.swing.JTable();
        btnPrevious = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNexr = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtDiemTrungBinh = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        pnnSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("MÃ SINH VIÊN : ");

        btnSearch.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\search-icon-16.png")); // NOI18N
        btnSearch.setText("Sreach");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnnSearchLayout = new javax.swing.GroupLayout(pnnSearch);
        pnnSearch.setLayout(pnnSearchLayout);
        pnnSearchLayout.setHorizontalGroup(
            pnnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnnSearchLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnnSearchLayout.setVerticalGroup(
            pnnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnnSearchLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearch)
                    .addComponent(txtMaSinhVien))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblTenSinhVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSinhVien.setText("Tên Sinh Viên : ");

        lblTenSV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSV.setText("Mã SV : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setText("Tiếng Anh  : ");

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setText("Tin Học : ");

        lblSDT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT1.setText("GDTC  : ");

        btnNewDST.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\new-icon-16.png")); // NOI18N
        btnNewDST.setText("New");
        btnNewDST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDSTActionPerformed(evt);
            }
        });

        txtTenSinhVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenSinhVienFocusLost(evt);
            }
        });

        txtMaSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaSVFocusLost(evt);
            }
        });

        txtTiengAnh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTiengAnhFocusLost(evt);
            }
        });

        txtTinHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTinHocFocusLost(evt);
            }
        });

        txtGDTC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGDTCFocusLost(evt);
            }
        });

        btnSaveDSV.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Save-icon.png")); // NOI18N
        btnSaveDSV.setText("Save");
        btnSaveDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDSVActionPerformed(evt);
            }
        });

        btnUpdateDSV.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Actions-document-edit-icon-16.png")); // NOI18N
        btnUpdateDSV.setText("Update");
        btnUpdateDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDSVActionPerformed(evt);
            }
        });

        btnDeleteDSV.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Actions-edit-delete-icon-16.png")); // NOI18N
        btnDeleteDSV.setText("Delete");
        btnDeleteDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDSVActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Button-Close-icon-16.png")); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblScoreST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblScoreST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblScoreSTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblScoreST);

        btnPrevious.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Button-First-icon-48.png")); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Fast-backward-icon2-48.png")); // NOI18N

        btnNexr.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Fast-forward-icon-48.png")); // NOI18N

        btnEnd.setIcon(new javax.swing.ImageIcon("D:\\SOF203_SD18317\\ASSIGNMENT_HT\\src\\main\\java\\poly\\edu\\icons\\Button-Last-icon-48.png")); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblTitle.setText("ĐIỂM TB : ");

        txtDiemTrungBinh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDiemTrungBinh.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiemTrungBinh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiemTrungBinh, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 0, 51));
        lblTitle1.setText("QUẢN LÍ ĐIỂM SINH VIÊN ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblTenSinhVien)
                                    .addComponent(lblTenSV)
                                    .addComponent(lblSDT1)
                                    .addComponent(btnPrevious)
                                    .addComponent(lblSDT))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTiengAnh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTenSinhVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMaSV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnLast)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNexr)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnEnd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNewDST, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnSaveDSV, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnUpdateDSV, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnDeleteDSV, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTitle1)
                    .addContainerGap(504, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteDSV, btnExit, btnNewDST, btnSaveDSV, btnUpdateDSV});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenSinhVien)
                                    .addComponent(txtTenSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenSV)
                                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail)
                                    .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSDT)
                                    .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSDT1)
                                    .addComponent(txtGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrevious)
                            .addComponent(btnLast)
                            .addComponent(btnNexr)
                            .addComponent(btnEnd))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewDST)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveDSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateDSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteDSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(641, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteDSV, btnExit, btnNewDST, btnSaveDSV, btnUpdateDSV});

    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewDSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDSTActionPerformed
        txtMaSinhVien.requestFocus();
        txtMaSV.setText("");
        txtTenSinhVien.setText("");
        txtTiengAnh.setText("");
        txtTinHoc.setText("");
        txtGDTC.setText("");

    }//GEN-LAST:event_btnNewDSTActionPerformed

    private void tblScoreSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblScoreSTMouseClicked
        try {
            index = tblScoreST.getSelectedRow();
            if (index >= 0 && index < tblScoreST.getRowCount()) {
                showDetail();
                txtTiengAnhFocusLost(null);
                txtTinHocFocusLost(null);
                txtGDTCFocusLost(null);
                txtTenSinhVienFocusLost(null);
            } else {
                JOptionPane.showMessageDialog(this, "Chưa có phần tử nào được chọn");
                return;
            }
        } catch (Exception e) {
            // Xử lý nếu có lỗi xảy ra
        }
    }//GEN-LAST:event_tblScoreSTMouseClicked
    public boolean checkEmty() {
        StringBuilder sb = new StringBuilder();
        if (txtMaSV.getText().equals("")) {
            sb.append("Mã SV đang trống !\n");
        }
        if (txtTiengAnh.getText().isEmpty()) {
            sb.append("Điểm Tiếng Anh trống!\n");
        } else {
            String check = txtTiengAnh.getText().trim();
            // Sử dụng biểu thức chính quy để kiểm tra xem chuỗi chỉ chứa số và dấu chấm hay không
            if (!check.matches("^[0-9.]*$")) {
                sb.append("Điểm Tiếng Anh không hợp lệ, chỉ được chứa các kí tự số !\n");
            }
        }

        if (txtTinHoc.getText().isEmpty()) {
            sb.append("Điểm Tin Học trống!\n");
        } else {
            String check = txtTiengAnh.getText().trim();
            // Sử dụng biểu thức chính quy để kiểm tra xem số điện thoại có chỉ chứa kí tự số hay không
            if (!check.matches("^[0-9.]*$")) {
                sb.append("Giá trị không hợp lệ, chỉ được chứa các kí tự số!\n");
            }
        }
        if (txtGDTC.getText().isEmpty()) {
            sb.append("Điểm GDTC trống!\n");
        } else {
            String check = txtGDTC.getText().trim();
            // Sử dụng biểu thức chính quy để kiểm tra xem số điện thoại có chỉ chứa kí tự số hay không
            if (!check.matches("^[0-9.]*$")) {
                sb.append("Giá trị không hợp lệ, chỉ được chứa các kí tự số!\n");
            }
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
            return true;
        }
        return false;
    }
    private void btnSaveDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDSVActionPerformed
        try {
            if (checkEmty()) {
                return;
            }
            GRADES d = GradeMethod();

            if (gds.findByid(txtMaSV.getText()) != null) {
                int chon = JOptionPane.showConfirmDialog(this, "Sinh viên đã tồn tại , Bạn có muốn update không ? ", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (chon != JOptionPane.YES_OPTION) {
                    return;
                } else {
                    if (gds.upDateDiemSinhVien(d)) {
                        JOptionPane.showMessageDialog(this, "Update thành công !");
                        LoadToTable();
                        return;
                    } else {
                        JOptionPane.showMessageDialog(this, "Update thất bại !");
                        return;
                    }
                }
            } else {
                if (gds.themDiemSinhVien(d)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công !");
                    LoadToTable();
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại  !");
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnSaveDSVActionPerformed

    private void btnUpdateDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDSVActionPerformed
        try {
            if (checkEmty()) {
                return;
            }
            GRADES d = GradeMethod();
            if (gds.upDateDiemSinhVien(d)) {
                JOptionPane.showMessageDialog(this, "Update thành công !");
                LoadToTable();
//                tinhdiemTB();

                return;
            } else {
                JOptionPane.showMessageDialog(this, "Update bảng điểm thất bại !");
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnUpdateDSVActionPerformed

    private void btnDeleteDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDSVActionPerformed
        try {
            if (checkEmty()) {
                return;
            }
            String MaSV = txtMaSV.getText().trim();
            GRADES d = GradeMethod();
            if (gds.deLeteDiemSinhVien(MaSV)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công !");
                LoadToTable();
//                tinhdiemTB();
                btnNewDSTActionPerformed(evt);
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Xóa bảng điểm thất bại !");
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnDeleteDSVActionPerformed

    private void txtMaSVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSVFocusLost
        try {

            GRADE_SERVICE gr = new GRADE_SERVICE();
            GRADES d = gr.findByid(txtMaSV.getText());

            if (d != null) {
                txtTiengAnh.setText(String.format("%.1f", d.getTiengAnh()));
                txtTinHoc.setText(String.format("%.1f", d.getTinHoc()));
                txtGDTC.setText(String.format("%.1f", d.getGDTC()));
                txtTenSinhVienFocusLost(null);
            } else {
//                JOptionPane.showMessageDialog(this, "Không tìm thấy mã sinh viên này ");
                return;
            }
        } catch (Exception e) {
            System.out.println("Lỗi" + e);
        }
    }//GEN-LAST:event_txtMaSVFocusLost

    private void txtTiengAnhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTiengAnhFocusLost
        if (txtTiengAnh.equals("") || txtTinHoc.equals("") || txtGDTC.equals("")) {
            return;
        }
        float tienganh = Float.parseFloat(txtTiengAnh.getText());
        float tinhoc = Float.parseFloat(txtTinHoc.getText());
        float tgdtc = Float.parseFloat(txtGDTC.getText());
        float ketqua = (tienganh + tinhoc + tgdtc) / 3;
        String formattedKetQua = String.format("%.1f", ketqua); // Format ketqua to have two decimal places
        txtDiemTrungBinh.setText(formattedKetQua);
    }//GEN-LAST:event_txtTiengAnhFocusLost

    private void txtTinHocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTinHocFocusLost
        if (txtTiengAnh.equals("") || txtTinHoc.equals("") || txtGDTC.equals("")) {
            return;
        }
        float tienganh = Float.parseFloat(txtTiengAnh.getText());
        float tinhoc = Float.parseFloat(txtTinHoc.getText());
        float tgdtc = Float.parseFloat(txtGDTC.getText());
        float ketqua = (tienganh + tinhoc + tgdtc) / 3;
        String formattedKetQua = String.format("%.1f", ketqua); // Format ketqua to have two decimal places
        txtDiemTrungBinh.setText(formattedKetQua);
    }//GEN-LAST:event_txtTinHocFocusLost

    private void txtGDTCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGDTCFocusLost
        if (txtTiengAnh.equals("") || txtTinHoc.equals("") || txtGDTC.equals("")) {
            return;
        }
        float tienganh = Float.parseFloat(txtTiengAnh.getText());
        float tinhoc = Float.parseFloat(txtTinHoc.getText());
        float tgdtc = Float.parseFloat(txtGDTC.getText());
        float ketqua = (tienganh + tinhoc + tgdtc) / 3;
        String formattedKetQua = String.format("%.1f", ketqua); // Format ketqua to have two decimal places
        txtDiemTrungBinh.setText(formattedKetQua);
    }//GEN-LAST:event_txtGDTCFocusLost

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {

            GRADE_SERVICE gr = new GRADE_SERVICE();
            GRADES d = gr.findByid(txtMaSinhVien.getText());

            if (d != null) {
                txtMaSV.setText(d.getMasSV());
                txtTiengAnh.setText(String.format("%.1f", d.getTiengAnh()));
                txtTinHoc.setText(String.format("%.1f", d.getTinHoc()));
                txtGDTC.setText(String.format("%.1f", d.getGDTC()));
                txtTenSinhVienFocusLost(null);
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy mã sinh viên này ");
                return;
            }
        } catch (Exception e) {
            System.out.println("Lỗi" + e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtTenSinhVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenSinhVienFocusLost

        try {
            STUDENTS_SERVICE svr = new STUDENTS_SERVICE();
            STUDENTS st = svr.findById(txtMaSV.getText());

            if (st != null) {
                txtTenSinhVien.setText(st.getTenSV());
                return;
            }
        } catch (Exception e) {
            System.out.println("Lỗi" + e);
        }
    }//GEN-LAST:event_txtTenSinhVienFocusLost

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
           
    }//GEN-LAST:event_btnPreviousActionPerformed
    
    private GRADES GradeMethod() {
        GRADES d = new GRADES();
        d.setMasSV(txtMaSV.getText());
        d.setTiengAnh(Float.parseFloat(txtTiengAnh.getText()));
        d.setTinHoc(Float.parseFloat(txtTinHoc.getText()));
        d.setGDTC(Float.parseFloat(txtGDTC.getText()));

        return d;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteDSV;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewDST;
    private javax.swing.JButton btnNexr;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSaveDSV;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateDSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSDT1;
    private javax.swing.JLabel lblTenSV;
    private javax.swing.JLabel lblTenSinhVien;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JPanel pnnSearch;
    private javax.swing.JTable tblScoreST;
    private javax.swing.JTextField txtDiemTrungBinh;
    private javax.swing.JTextField txtGDTC;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtMaSinhVien;
    private javax.swing.JTextField txtTenSinhVien;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables

    private void LoadToTable() throws Exception {
        model.setRowCount(0);
        ArrayList<GRADES> list = gds.findByTop3(5);
        for (GRADES grades : list) {
            float diemtb = (grades.getTiengAnh() + grades.getTinHoc() + grades.getGDTC()) / 3;
            String format = String.format("%.1f", diemtb);
            model.addRow(new Object[]{
                grades.getId(), grades.getMasSV(), grades.getTiengAnh(),
                grades.getTinHoc(), grades.getGDTC(), diemtb
            });
        }
        String[] data = {
            "ID", "MÃ SINH VIÊN ", "TIẾNG ANH", "TIN HỌC", "GDTC", "DIEM TB"
        };
        model.setColumnIdentifiers(data);
    }

    private void showDetail() throws Exception {
        GRADES gr = new GRADES();
        txtMaSV.setText((String) tblScoreST.getValueAt(index, 1).toString());
        txtTiengAnh.setText((String) tblScoreST.getValueAt(index, 2).toString());
        txtTinHoc.setText((String) tblScoreST.getValueAt(index, 3).toString());
        txtGDTC.setText((String) tblScoreST.getValueAt(index, 4).toString());

    }

}
